import { OWNER_TAG } from "../../constants/ownerConstants";
import { TOwners } from "../../types/ownersTypes";
import { apiSlice } from "./apiSlice";

//assign tags for caching
const ownerApiWithTag = apiSlice.enhanceEndpoints({addTagTypes: [OWNER_TAG]})

//add endpoints for owners
export const ownersApiSlice = ownerApiWithTag.injectEndpoints({
  endpoints: builder => ({
    getOwners: builder.query<TOwners, void>({
      query: () => '/owners',
      providesTags: [OWNER_TAG] //for caching
    })
  })
})

/*hooks for endpoints are autogenerated*/
export const {
  useGetOwnersQuery
} = ownersApiSlice